// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaProjekt.Database;

namespace PizzaProjekt.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PizzaProjekt.Models.Ingredients", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("gruppe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            id = 1,
                            gruppe = "Meats",
                            name = "Salami"
                        },
                        new
                        {
                            id = 2,
                            gruppe = "Meats",
                            name = "Sucuk"
                        },
                        new
                        {
                            id = 3,
                            gruppe = "Meats",
                            name = "Schinken"
                        },
                        new
                        {
                            id = 4,
                            gruppe = "Vegetables",
                            name = "Pepperoni"
                        },
                        new
                        {
                            id = 5,
                            gruppe = "Vegetables",
                            name = "Tomaten"
                        },
                        new
                        {
                            id = 6,
                            gruppe = "Vegetables",
                            name = "Oliven"
                        },
                        new
                        {
                            id = 7,
                            gruppe = "Cheese",
                            name = "Mozzarella"
                        },
                        new
                        {
                            id = 8,
                            gruppe = "Cheese",
                            name = "Schafskäse"
                        },
                        new
                        {
                            id = 9,
                            gruppe = "Cheese",
                            name = "Parmesan"
                        });
                });

            modelBuilder.Entity("PizzaProjekt.Models.IngredientsOrders", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("IngredientsOrders");
                });

            modelBuilder.Entity("PizzaProjekt.Models.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nachname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<int>("postCode")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaProjekt.Models.Pizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Pizza Napoli"
                        },
                        new
                        {
                            id = 2,
                            name = "Pizza Roma"
                        });
                });

            modelBuilder.Entity("PizzaProjekt.Models.PizzaOrders", b =>
                {
                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("PizzaId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("PizzaOrders");
                });

            modelBuilder.Entity("PizzaProjekt.Models.IngredientsOrders", b =>
                {
                    b.HasOne("PizzaProjekt.Models.Ingredients", "Ingredients")
                        .WithMany("IngredientsOrders")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaProjekt.Models.Orders", "Orders")
                        .WithMany("IngredientsOrders")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaProjekt.Models.PizzaOrders", b =>
                {
                    b.HasOne("PizzaProjekt.Models.Orders", "Orders")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaProjekt.Models.Pizza", "Pizza")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
